### ISSUE TITLE
Remove MPI errors in METplus output

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#153] opened 2018-11-30 20:20 UTC
When METplus is run, many errors show up from MPI and clutter the output.

**Comment by georgemccabe** [comment] 2019-01-25 21:33
The line that is causing this long output is in ush/produtil/mpi_impl/impi.py, line 64:

version=produtil.run.runstr(produtil.run.exe(mpirun_path))

This calls mpirun, which spits out a usage statement since it is not supposed to be run this way. It is simply checking for the version, so it could be run as 'mpirun --version' instead. Also, this output could somehow not be output to the screen. The code looks like it is intended to capture the output to a variable and search for Intel, but the output also goes to std out.

**Comment by jimfrimel** [comment] 2019-12-04 15:56
Note: The original --version usage message referenced in the comment above  no-longer occurs since the METplus version of produtil is a subset of the full package: 

https://github.com/NOAA-EMC/NCEPLIBS-pyprodutil/tree/metplus-python3

However, there are still a set of INFO log messages at startup.
These INFO log messages  are NOT a bug and has always been a part of the package, 
my understanding is, this was intentionally put in place for NCO.

However,  some projects  prefer to suppress these mpi detection log messages, which is 
a very reasonable requirement.  As a stop gap,  temporarily commented out the log message until this can be  addressed to support both requirements.

Will close this ticket, as the message is now suppressed  247eb7a04bfa , however a new ticket will be created to address this requirement for a future release.

**Closed by jimfrimel** 2019-12-04 15:56 UTC
Labels: priority: high
